sudo: required
services:
  - docker
env:
  global:
    # SHA of last git commit
    - GIT_SHA=$(git rev-parse HEAD)
    # disable all prompts from gcloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # install google cloud on travis
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # gcloud > IAM & admin > service accounts > create service account
  # download file.json and encrypt file with travis
  # docker run -it -v $(pwd):/app ruby:2.3 /bin/bash
  # gem install travis
  # travis login
  # travis encrypt-file multi-docker.json -r ae1663830a/multi-docker-ci-cd
  # copy response command here and add encrypted file to git repo
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in multi-docker.json.enc -out multi-docker.json -d
  # authorization with created user in gcloud
  - gcloud auth activate-service-account --key-file multi-docker.json
  # gcloud project id (not name)
  - gcloud config set project multi-docker
  # gcloud cluster zone
  - gcloud config set compute/zone europe-north1-a
  # gcloud cluster name
  - gcloud container clusters get-credentials multi-cluster
  # Build image to run tests
  - docker build -t ae1663830a/front-test -f ./frontend/Dockerfile-dev ./frontend

script:
  - docker run ae1663830a/frontend-test npm run test -- --coverage

after_success:
  # Log in to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
