apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  # How many pods will be created
  replicas: 3
  selector:
    matchLabels:
      component: server
  # Pods will be created by config below
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: backend
          # Containers image repo from docker-hub
          image: ae1663830a/multi-backend
          ports:
            - containerPort: 5000
          env:
            # REDIS ENV VARIABLES
            - name: REDIS_HOST
              # name of redis-cluster-ip config
              value: redis-cluster-ip-service
            - name: REDIS_PORT
             # port of redis-cluster-ip
              value: 6379
            # POSTGRES ENV VARIABLES
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: 5432
            - name: PGDATABASE
              value: postgres
