apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # values can be ReadWrite, ReadOnly (Once | Many - indicates node number - one or many)
    # ReadWrite permission for a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
