apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  # How many pods will be created
  replicas: 1
  selector:
    matchLabels:
      component: postgresSQL
  # Pods will be created by config below
  template:
    metadata:
      labels:
        component: postgresSQL
    spec:
      # Assigning persistent volume
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          # Containers image repo from docker-hub
          image: ae1663830a/multi-postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - # Choose the volume from volumes part ^
              name: postgres-storage
              # Location where postgres stores data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            # env variable in postgres container
            - name: PGPASSWORD
              valueFrom:
                # Secret object in k8s
                secretKeyRef:
                  # secret name
                  name: pgpassword
                  # key which stores password value
                  key: PGPASSWORD
